# Generated by Django 2.2.1 on 2019-06-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
    ]
